# Generated by Django 3.1.7 on 2021-05-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_number', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=50)),
                ('identity_document_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_onset_of_symptoms', models.DateField()),
                ('date_of_confirmation_of_infection_by_testing', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_the_event', models.DateField()),
                ('venue_name', models.CharField(max_length=50)),
                ('venue_location', models.CharField(max_length=256)),
                ('address_of_the_venue_location', models.CharField(max_length=256)),
                ('hk1980_grid_coordinates_of_the_venue_location', models.CharField(max_length=256)),
                ('description_of_the_event', models.CharField(max_length=256)),
                ('count', models.IntegerField(default=0)),
                ('Cases', models.ManyToManyField(to='trial_delete_later.Case')),
            ],
        ),
    ]
