# Generated by Django 3.1.7 on 2021-04-29 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_number', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=50)),
                ('identity_document_number', models.CharField(default='0000000', max_length=50, unique=True)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_of_onset_of_symptoms', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_of_confirmation_of_infection_by_testing', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_the_event', models.DateField()),
                ('vanue_name', models.CharField(max_length=50)),
                ('vanue_location', models.CharField(max_length=256)),
                ('address_of_the_venue_location', models.CharField(max_length=256)),
                ('hk1980_grid_coordinates_of_the_venue_location', models.CharField(max_length=256)),
                ('description_of_the_event', models.CharField(max_length=256)),
                ('count', models.IntegerField(default=0)),
                ('Cases', models.ManyToManyField(to='trial_delete_later.Case')),
            ],
        ),
    ]
