# Generated by Django 3.1.7 on 2021-05-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_delete_later', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='identify_document_number',
            field=models.CharField(max_length=50),
        ),
    ]
