# Generated by Django 3.1.7 on 2021-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_delete_later', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Cases',
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
