# Generated by Django 3.1.7 on 2021-05-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_delete_later', '0002_auto_20210502_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Cases',
            field=models.ManyToManyField(to='trial_delete_later.Case'),
        ),
    ]
