# Generated by Django 3.1.7 on 2021-05-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial_delete_later', '0002_auto_20210502_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='identity_document_number',
            new_name='identify_document_number',
        ),
    ]
